# Use root/example as user/password credentials

services:

  mynodered:
    image: nodered/node-red
    container_name: mynodered
    restart: no
    ports:
      - 1880:1880
    networks:
      - iot

  mydb:
    image: mariadb
    container_name: mydb
    restart: no
    environment:
      MARIADB_ROOT_PASSWORD: example
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - iot

  myadminer:
    image: adminer
    container_name: myadminer
    restart: no
    ports:
      - 8080:8080
    networks:
      - iot

networks:
  iot:
    external: true
